# Generated by Django 3.0.8 on 2020-07-13 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Post Title')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('dateCreated', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('lastUpdated', models.DateField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
