# Generated by Django 3.0.8 on 2020-07-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
