# Generated by Django 3.0.8 on 2020-07-14 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200713_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Post Content')),
                ('lastUpdated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
