# Generated by Django 3.0.8 on 2020-08-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aboutmepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
