# Generated by Django 3.0.8 on 2020-08-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_datepublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='datePublished',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
    ]
