# Generated by Django 3.0.8 on 2020-08-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200809_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='datePublished',
            field=models.DateTimeField(null=True, verbose_name='Date Published'),
        ),
    ]
