# Generated by Django 3.0.8 on 2020-08-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200809_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='datePublished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Published'),
        ),
    ]
