# Generated by Django 3.0.8 on 2020-08-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200809_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published',
        ),
    ]
